Repository jgetzel/cse110-w21-group21, pull requests merged in 2021-03, with the labels that each got.

#92 adr for source code organization
  admin/adr/2-source_code_organization.md
Labels: documentation

#117 light / dark mode and more rotating background photos
  __tests__/components/button.test.js
  __tests__/utils/theme.test.js
  jest.config.js
  package-lock.json
  package.json
  source/assets/images/backgrounds/day/bg0.jpg
  source/assets/images/backgrounds/day/bg1.jpg
  source/assets/images/backgrounds/day/bg2.jpg
  source/assets/images/backgrounds/day/bg3.jpg
  source/assets/images/backgrounds/day/bg4.jpg
  source/assets/images/backgrounds/day/bg5.jpg
  source/assets/images/backgrounds/night/bg0.jpg
  source/assets/images/backgrounds/night/bg1.jpg
  source/assets/images/backgrounds/night/bg2.jpg
  source/assets/images/backgrounds/night/bg3.jpg
  source/assets/images/backgrounds/night/bg4.jpg
  source/assets/images/backgrounds/night/bg5.jpg
  source/assets/scripts/components/button/button.js
  source/assets/scripts/components/header/header.js
  source/assets/scripts/history.js
  source/assets/scripts/main.js
  source/assets/scripts/timer.js
  source/assets/scripts/utils/theme.js
  source/assets/styles/base.css
  source/assets/styles/button.css
  source/history.html
  source/index.html
  source/task.html
  source/timer.html
Labels: CSS, enhancement

#119 Fixed progress circle bug
  __tests__/components/header.test.js
  source/assets/scripts/components/header/header.js
  source/assets/scripts/components/progress-circle/progress-circle.js
  source/assets/scripts/timer.js
  source/assets/svgImages/logo.svg
  source/history.html
  source/index.html
  source/timer.html
Labels: JS, bug, enhancement

#116 Prompt user about exiting page
  cypress/integration/timer/leaving-active-session.js
  source/assets/scripts/components/header/header.js
  source/assets/scripts/database/session.js
  source/assets/scripts/main.js
  source/assets/scripts/timer.js
Labels: JS, bug
